//----------------------
// <auto-generated>
//     Cleaned: No endpoints present
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

// No endpoints available. Add controllers to your backend to generate API client code.
